{{- if eq .Values.config.storage.engine "blocks" -}}
{{- if not .Values.topologyAware.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-store-gateway.headlessname" . }}
  labels: {{ include "cortex-store-gateway.labels" . | nindent 4 }}
    {{- with .Values.store_gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.store_gateway.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector: {{- include "cortex-store-gateway.matchLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.topologyAware.enabled }}
{{- range $availabilityCell := .Values.store_gateway.availabilityCells }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-store-gateway.headlessname-zone-aware" dict "Values" $.Values "Release" $.Release "Chart" $.Chart "AvailabilityCell" $availabilityCell.name }}
  labels: {{ include "cortex-store-gateway.labels" $ | nindent 4 }}
    {{- with $.Values.store_gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $.Values.store_gateway.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ $.Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector: {{- include "cortex-store-gateway.matchLabels" $ | nindent 4 }}
    {{ $.Values.topologyAware.zoneLabel }}: {{ $availabilityCell.name }}
---
{{- end }}
{{- end }}
{{- end -}}