{{- if eq .Values.config.storage.engine "blocks" -}}
{{- if not .Values.topologyAware.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-store-gateway.fullname" . }}
  labels: {{ include "cortex-store-gateway.labels" . | nindent 4 }}
    {{- with .Values.store_gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.store_gateway.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector: {{- include "cortex-store-gateway.matchLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.topologyAware.enabled }}
{{- range $availabilityCell := .Values.topologyAware.availabilityCells }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-store-gateway.fullname" $ }}-{{ $availabilityCell }}
  labels: {{ include "cortex-store-gateway.labels" $ | nindent 4 }}
    {{- with $.Values.store_gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{ $.Values.topologyAware.zoneLabel }}: {{ $availabilityCell }}
  annotations:
    {{- toYaml $.Values.store_gateway.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ $.Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector: {{- include "cortex-store-gateway.matchLabels" $ | nindent 4 }}
    {{ $.Values.topologyAware.zoneLabel }}: {{ $availabilityCell }}
---
{{- end }}
{{- end }}
{{- end -}}