apiVersion: v2
version: 0.5.4
appVersion: v1.11.1
description: 'Horizontally scalable, highly available, multi-tenant, long term Prometheus.'
home: https://cortexmetrics.io/
icon: https://avatars2.githubusercontent.com/u/43045022?s=200&v=4
kubeVersion: ^1.19.0-0
maintainers:
  - email: thayward@infoblox.com
    name: Tom Hayward
    url: https://github.com/kd7lxl
  - email: Niclas.Schad@plusserver.com
    name: Niclas Schad
    url: https://github.com/ShuzZzle
name: cortex
sources:
  - https://github.com/cortexproject/cortex-helm-chart
dependencies:
  - name: memcached
    alias: memcached
    version: 6.0.17
    repository: https://charts.bitnami.com/bitnami
    condition: memcached.enabled
  - name: memcached
    alias: memcached-index-read
    version: 6.0.17
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-index-read.enabled
  - name: memcached
    alias: memcached-index-write
    version: 6.0.17
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-index-write.enabled

  - name: memcached
    alias: memcached-frontend
    version: 6.0.17
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-frontend.enabled

  - name: memcached
    alias: memcached-index
    version: 6.0.17
    repository: https://charts.bitnami.com/bitnami
    tags:
      - blocks-storage-memcached
  - name: memcached
    alias: memcached-chunks
    version: 6.0.17
    repository: https://charts.bitnami.com/bitnami
    tags:
      - blocks-storage-memcached
  - name: memcached
    alias: memcached-metadata
    version: 6.0.17
    repository: https://charts.bitnami.com/bitnami
    tags:
      - blocks-storage-memcached

  - name: consul
    version: 0.31.1
    repository: https://helm.releases.hashicorp.com
    condition: consul.enabled

  - name: rollout-operator
    version: 0.1.2
    repository: https://grafana.github.io/helm-charts
    condition: topologyAware.rolloutOperator.enabled
