{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "cortex.fullname" . }}
  labels: {{ include "cortex.labels" . | nindent 4 }}
{{- if and .Values.rbac.pspEnabled (le (int .Capabilities.KubeVersion.Minor) 24) }}
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "cortex.fullname" . }}]
{{- end }}
{{- end }}

